language: node_js
node_js:
- '0.8'
- '0.10'
- '0.11'
deploy:
  provider: npm
  email:
    secure: oTwdZl7lHSHGe/2weK33uj2oKRCWJslT/mN6RE7poX40VGCF+sn/ShgeXSeOyJClo/2rrZRfRyTJRf4/0qtnEY9GgeWyj+pQf4ttF1QM3emTjpQdlaMFrt9O5+kswmuugyNmw5IJQukic6PRDejjjkSstTi6SAoXSAw+Xz0C3Uk=
  password:
    secure: QKlShFaFxE3OR7zsT9Jhc7fn8KNWpvlMnlzAROuWs55OlYKsLnelAa8qppp27YToUtqcXRI73PKQFDOpWDFFjP4VNGd+xnd1PPYF0lY6HzUHjVYi5T+xpzPNY88VLjYnud+phaFpRdLZ1lB1+hp2FswWouqFuP+oEhjVgq9ClKk=
  on:
    branch: master
